<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Planfree-trial</name>
   <tag></tag>
   <elementGuidId>1c89e2fe-f839-40f6-a3e5-44ca10332f9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.flex.items-center.justify-between.w-full</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='radix-:ReamH1:']/div[5]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>842d1ad7-16d9-48cf-834d-147af1771e6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center justify-between w-full</value>
      <webElementGuid>5226f690-42b2-435a-8715-060fd5139e72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Planfree-trial</value>
      <webElementGuid>042f683b-5a79-46f5-9726-09442004a762</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:ReamH1:&quot;)/div[@class=&quot;relative flex cursor-pointer select-none items-center rounded-sm px-2 py-1.5 text-sm outline-none transition-colors focus:bg-accent focus:text-accent-foreground data-[disabled]:pointer-events-none data-[disabled]:opacity-50&quot;]/span[@class=&quot;flex items-center justify-between w-full&quot;]</value>
      <webElementGuid>4ee2f7b1-6d91-4a80-93fe-d0615bf906b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:ReamH1:']/div[5]/span</value>
      <webElementGuid>9975f338-77ef-4023-8405-e8ead6666226</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Billing'])[1]/following::span[1]</value>
      <webElementGuid>01ec733a-803c-453f-bd4b-ea0f1e46f7e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile'])[1]/following::span[2]</value>
      <webElementGuid>31d75af0-08b1-4c6c-bd13-12fed921919e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/preceding::span[1]</value>
      <webElementGuid>9ca84ef6-ef7f-49cc-b0fd-3074dc409cdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/span</value>
      <webElementGuid>bd380286-4a5c-4289-b121-66087e56cfcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Planfree-trial' or . = 'Planfree-trial')]</value>
      <webElementGuid>c54ef190-a7ff-456c-98de-9fc7990103e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
