<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Features</name>
   <tag></tag>
   <elementGuidId>f1a5eaf8-090f-4ecb-9907-1b114ca853b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/section/header/header/div/div/nav/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e8bef405-831f-424a-a1ec-dc4b85c18819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>transition-all dark:hover:text-primary-200 relative after:w-0 hover:after:w-full after:h-0.5 after:bg-white after:absolute after:left-0 after:-bottom-1 after:transition-all</value>
      <webElementGuid>f17e59f0-e975-4419-94dc-c2f34b2463bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/#features</value>
      <webElementGuid>42ead5b9-bccc-4ba1-8f09-17c86bfcbaf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Features</value>
      <webElementGuid>fc270804-b098-4b5e-abce-3a9ad6a208f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;app&quot;]/section[@class=&quot;min-h-0 bg-neutral-100 lg:flex lg:flex-col&quot;]/header[@class=&quot;z-50 top-0 left-0 w-full fixed w-full&quot;]/header[@class=&quot;py-3 2xl:py-5 transition-all z-50 undefined bg-transparent text-white dark:text-white dark:bg-neutral-900&quot;]/div[@class=&quot;px-5 mx-auto container flex items-center justify-between&quot;]/div[@class=&quot;flex gap-10 items-center&quot;]/nav[@class=&quot;hidden md:flex gap-10 items-center&quot;]/a[@class=&quot;transition-all dark:hover:text-primary-200 relative after:w-0 hover:after:w-full after:h-0.5 after:bg-white after:absolute after:left-0 after:-bottom-1 after:transition-all&quot;]</value>
      <webElementGuid>bb414790-ae0f-4d56-ba5f-2729e7905ac7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section/header/header/div/div/nav/a[2]</value>
      <webElementGuid>d2fb6f9e-d847-4dc1-8d58-9a3fd02d1bf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Features')]</value>
      <webElementGuid>b46286d0-c4a7-4f52-b0b3-f7482031adbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::a[1]</value>
      <webElementGuid>178189c4-2a31-4c40-b188-23a9b3a83054</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pricing'])[1]/preceding::a[1]</value>
      <webElementGuid>c6362ae3-7466-4283-a002-4178ea6f2771</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='News'])[1]/preceding::a[2]</value>
      <webElementGuid>fb4ffc2b-5329-4c5f-97af-e7db0f1e8328</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Features']/parent::*</value>
      <webElementGuid>22e63ab0-8d0d-45ed-9af5-9d275c32c1d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/#features')]</value>
      <webElementGuid>93e52825-409b-4c46-a884-1d033d163a76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>ff993d87-ab37-4b9a-8105-119e50ad91d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/#features' and (text() = 'Features' or . = 'Features')]</value>
      <webElementGuid>fe590ca2-e23e-488b-8d17-c97c4ef55701</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
