<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_News</name>
   <tag></tag>
   <elementGuidId>a1f384ca-9d66-4d05-9088-9bd3bb161a93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/section/header/header/div/div/nav/a[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>30fdc451-1c7c-4db0-9401-daa55311fcf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>transition-all dark:hover:text-primary-200 relative after:w-0 hover:after:w-full after:h-0.5 after:bg-white after:absolute after:left-0 after:-bottom-1 after:transition-all</value>
      <webElementGuid>1220c0b3-3582-4045-a949-8c62ce79b46a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/news</value>
      <webElementGuid>f5f6a137-c23c-4e39-ab45-0a798ef9391d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>News</value>
      <webElementGuid>4747d4a7-9b0e-40da-aa45-334993b89996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;app&quot;]/section[@class=&quot;min-h-0 bg-neutral-100 lg:flex lg:flex-col&quot;]/header[@class=&quot;z-50 top-0 left-0 w-full fixed w-full&quot;]/header[@class=&quot;py-3 2xl:py-5 transition-all z-50 undefined bg-white text-black dark:text-white shadow-md dark:bg-neutral-900&quot;]/div[@class=&quot;px-5 mx-auto container flex items-center justify-between&quot;]/div[@class=&quot;flex gap-10 items-center&quot;]/nav[@class=&quot;hidden md:flex gap-10 items-center&quot;]/a[@class=&quot;transition-all dark:hover:text-primary-200 relative after:w-0 hover:after:w-full after:h-0.5 after:bg-white after:absolute after:left-0 after:-bottom-1 after:transition-all&quot;]</value>
      <webElementGuid>e081fa72-65d4-4e76-ab6c-9dd0ad81b3b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section/header/header/div/div/nav/a[4]</value>
      <webElementGuid>17c23443-086d-4d74-a523-dec1eb39abb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'News')]</value>
      <webElementGuid>26f0b9cb-da95-4454-a8ec-e3371b241546</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pricing'])[1]/following::a[1]</value>
      <webElementGuid>96909c78-ea0f-4d41-9dda-e16ead070415</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Features'])[1]/following::a[2]</value>
      <webElementGuid>449a5925-cadc-460f-93a4-dc571d78aed2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Documentation'])[1]/preceding::a[1]</value>
      <webElementGuid>704dd7ae-2b6e-459f-b485-d9ba5769d115</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign In to Console'])[1]/preceding::a[2]</value>
      <webElementGuid>22982ad6-2440-4818-9a05-c60069d946d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='News']/parent::*</value>
      <webElementGuid>de407ecf-931b-424d-8249-226717ea4683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/news')]</value>
      <webElementGuid>7786263e-7aa0-4382-b63b-f1cfdaedda7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]</value>
      <webElementGuid>c466a981-b5b1-465d-8e01-f39364c5aed2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/news' and (text() = 'News' or . = 'News')]</value>
      <webElementGuid>be4322f4-4d89-4b15-a335-f86e1b7c3121</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
