<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Pricing</name>
   <tag></tag>
   <elementGuidId>45370d28-70cb-4504-9bca-7144be3bc6b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/section/header/header/div/div/nav/a[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3f8ad773-b635-4bfe-a4b3-6948a7db1621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>transition-all dark:hover:text-primary-200 relative after:w-0 hover:after:w-full after:h-0.5 after:bg-white after:absolute after:left-0 after:-bottom-1 after:transition-all</value>
      <webElementGuid>b1736026-2f86-4a2f-bbd7-f4df58c013ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/pricing</value>
      <webElementGuid>e5566da5-ad64-4e3e-ac29-af0e75a268c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pricing</value>
      <webElementGuid>b542e68e-abca-4349-9d7f-5346be8a1583</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;app&quot;]/section[@class=&quot;min-h-0 bg-neutral-100 lg:flex lg:flex-col&quot;]/header[@class=&quot;z-50 top-0 left-0 w-full fixed w-full&quot;]/header[@class=&quot;py-3 2xl:py-5 transition-all z-50 undefined bg-white text-black dark:text-white shadow-md dark:bg-neutral-900&quot;]/div[@class=&quot;px-5 mx-auto container flex items-center justify-between&quot;]/div[@class=&quot;flex gap-10 items-center&quot;]/nav[@class=&quot;hidden md:flex gap-10 items-center&quot;]/a[@class=&quot;transition-all dark:hover:text-primary-200 relative after:w-0 hover:after:w-full after:h-0.5 after:bg-white after:absolute after:left-0 after:-bottom-1 after:transition-all&quot;]</value>
      <webElementGuid>32837a81-44a4-4b0d-978b-ec6a3669d4c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section/header/header/div/div/nav/a[3]</value>
      <webElementGuid>c12fc36a-c4c2-46b9-a685-3d2f828e915b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Pricing')]</value>
      <webElementGuid>aef77cce-a3af-4749-a642-2b528f879b97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Features'])[1]/following::a[1]</value>
      <webElementGuid>28da2536-c877-4cb7-a3ba-b974fc87cd27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::a[2]</value>
      <webElementGuid>c2743b9c-fef3-403d-92f0-47093f880ad1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='News'])[1]/preceding::a[1]</value>
      <webElementGuid>53d8dd88-b17f-4dcd-8610-494316081a9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Documentation'])[1]/preceding::a[2]</value>
      <webElementGuid>1fe2d7c2-60db-4581-9427-d1d7137ce754</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pricing']/parent::*</value>
      <webElementGuid>3ae33f1d-7b9c-4e3b-b817-590f7fb32e83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/pricing')]</value>
      <webElementGuid>21fb4804-3b70-4f9f-9c0e-4d9bb4ff5e35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]</value>
      <webElementGuid>53b2ed28-fa4b-458a-8cdc-428c27a31068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/pricing' and (text() = 'Pricing' or . = 'Pricing')]</value>
      <webElementGuid>ee7acb8f-f13e-4e9c-bfe6-274179ba829e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
