<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Ethereum</name>
   <tag></tag>
   <elementGuidId>af796d78-d104-4310-9999-f583d5bbaa85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='headlessui-tabs-tab-:ri:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cc308e9a-a8cb-45c3-9897-3ab431606d57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex p-2 outline-none text-neutral-500 cursor-pointer false</value>
      <webElementGuid>af5a9b73-e680-44d9-bfe7-afb4183c1a47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headlessui-tabs-tab-:ri:</value>
      <webElementGuid>35deb334-aa68-4bf4-a13d-97d52693209c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>3f015a35-c331-47dd-892f-06cb1bd68626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4b2b1e27-1728-4100-b280-ec0eefbfe6b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>071f7047-e2aa-4180-bb41-de00b11317bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>headlessui-tabs-panel-:rk:</value>
      <webElementGuid>13117a2b-2d1b-4892-a1f1-bda4469c5590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ethereum</value>
      <webElementGuid>31e9a9c3-0348-416f-bc93-5e8bcdc3e9c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-tabs-tab-:ri:&quot;)</value>
      <webElementGuid>32c34ae9-3b29-4c7f-86eb-657508600bbd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='headlessui-tabs-tab-:ri:']</value>
      <webElementGuid>c38e6271-49f7-45a9-b1f7-ebc196fccf4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section/main/div/section[5]/div[2]/div/div/div/div[2]</value>
      <webElementGuid>14603e32-40d3-4af0-880d-f0ca938b4b1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hyperledger Fabric'])[1]/following::div[1]</value>
      <webElementGuid>90eb8d1f-ce63-4d01-a99a-35ca78dcf3df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blockchain Framework'])[1]/following::div[3]</value>
      <webElementGuid>3b1dbb0d-df95-4d0e-8f54-713f66a74c21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ready for blockchain transformations?'])[1]/preceding::div[8]</value>
      <webElementGuid>963859b3-40fd-40bf-9f56-e6e8f0b5d203</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ready, get started'])[1]/preceding::div[9]</value>
      <webElementGuid>7e352138-ed32-4e90-a1ef-189ce6ced0aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ethereum']/parent::*</value>
      <webElementGuid>9902e1d0-0586-480b-af9d-d990bad14e67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[5]/div[2]/div/div/div/div[2]</value>
      <webElementGuid>6b4c6806-dc62-4533-849a-2bf232759880</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'headlessui-tabs-tab-:ri:' and (text() = 'Ethereum' or . = 'Ethereum')]</value>
      <webElementGuid>fe575100-4234-408f-9c60-cdd98adfaddc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
