<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Hyperledger Fabric</name>
   <tag></tag>
   <elementGuidId>796641dd-def3-432e-8b75-7cccac757c8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='headlessui-tabs-tab-:rh:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>485d0277-7947-4873-91f6-224e96f754b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex p-2 outline-none text-neutral-500 cursor-pointer false</value>
      <webElementGuid>5f7b7012-3d0a-46fd-ad3d-e08233d9762d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headlessui-tabs-tab-:rh:</value>
      <webElementGuid>b41db286-3f85-4c4d-9c28-43e0e4d1310d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>39e63c32-f925-41bb-9562-fa2595c6ebb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a5529c3d-ec9c-468e-847d-10885181c96c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>c3557de6-a629-4e79-8900-82d164e0a699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>headlessui-tabs-panel-:rj:</value>
      <webElementGuid>10d59e2d-1be9-4009-ad58-eeedcc5fbd49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hyperledger Fabric</value>
      <webElementGuid>f9c8c92b-9ca5-4748-be76-d0b4e22d7e94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-tabs-tab-:rh:&quot;)</value>
      <webElementGuid>1f1b2141-6722-40d4-a152-c1bd47be0c3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='headlessui-tabs-tab-:rh:']</value>
      <webElementGuid>abe8329e-4896-4cdc-880d-58522d0b5f30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section/main/div/section[5]/div[2]/div/div/div/div</value>
      <webElementGuid>c1e483ca-0ae1-463d-9b72-7d02acbb805a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blockchain Framework'])[1]/following::div[2]</value>
      <webElementGuid>8b62e2d2-874f-41b3-b887-993770208547</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explore our product'])[1]/following::div[6]</value>
      <webElementGuid>51e205e2-e0d0-4d5d-9f3a-7e12995d7a3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ethereum'])[1]/preceding::div[1]</value>
      <webElementGuid>f7d8b3f6-9cd9-4c80-a757-6a58d3efcbb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ready for blockchain transformations?'])[1]/preceding::div[9]</value>
      <webElementGuid>2f5804f8-3a95-4b85-8631-41efc1701415</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hyperledger Fabric']/parent::*</value>
      <webElementGuid>ea40889c-c25f-4617-be78-59dd1559e836</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[5]/div[2]/div/div/div/div</value>
      <webElementGuid>b9f0930a-17cb-4d03-bf31-ef36d204885e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'headlessui-tabs-tab-:rh:' and (text() = 'Hyperledger Fabric' or . = 'Hyperledger Fabric')]</value>
      <webElementGuid>988c37ca-ae72-4e6d-bf31-5db9ee872c2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
