<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Deployment Options on Your Choice</name>
   <tag></tag>
   <elementGuidId>e8117dd3-499e-4284-970c-d1fbfadad3e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='headlessui-tabs-tab-:r5:']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5701ddf8-6874-4bcd-a54e-6cd528115faa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex justify-between px-5 py-3 w-full bg-white border-b </value>
      <webElementGuid>4bdac27e-7ee8-4fdd-83ac-ca8b83b77a55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Deployment Options on Your Choice</value>
      <webElementGuid>dbf0794f-0742-4c14-abb6-7e86afa89253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-tabs-tab-:r5:&quot;)/div[@class=&quot;flex justify-between px-5 py-3 w-full bg-white border-b&quot;]</value>
      <webElementGuid>d7ac5ffa-5cf1-4b7d-9a3f-57820f137c08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='headlessui-tabs-tab-:r5:']/div</value>
      <webElementGuid>bdc4e5e3-81a1-4776-8b14-083d1910b00f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RESTful API'])[1]/following::div[4]</value>
      <webElementGuid>4cb5ab50-9df5-4f3b-97b3-58d9cc5f1105</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simple and Intuitive User Interface'])[1]/following::div[9]</value>
      <webElementGuid>a1ad3fba-375a-499f-94a0-f69f1cf259a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Support Various Blockchain Protocols'])[1]/preceding::div[4]</value>
      <webElementGuid>657b9b6b-fce7-426a-8661-8e2bdc7b395b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button/div</value>
      <webElementGuid>c5857e2d-4a86-43cf-a28a-80d732fd22f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Deployment Options on Your Choice' or . = 'Deployment Options on Your Choice')]</value>
      <webElementGuid>a179a64a-e137-44e7-92b4-dc3b8df59bcb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
